// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id <project-id> > src/types/supabase.ts
// or: npx supabase gen types typescript --local > src/types/supabase.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      recipes: {
        Row: {
          id: string
          title: string
          ingredients: string[]
          steps: string[]
          meal_type: string | null
          original_prompt_ingredients: string[] | null
          refinement_instruction: string | null
          parent_recipe_id: string | null
          ai_model_used: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          ingredients: string[]
          steps: string[]
          meal_type?: string | null
          original_prompt_ingredients?: string[] | null
          refinement_instruction?: string | null
          parent_recipe_id?: string | null
          ai_model_used?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          ingredients?: string[]
          steps?: string[]
          meal_type?: string | null
          original_prompt_ingredients?: string[] | null
          refinement_instruction?: string | null
          parent_recipe_id?: string | null
          ai_model_used?: string | null
          created_at?: string
          updated_at?: string
        }
      }

      user_favorites: {
        Row: {
          id: string
          user_id: string
          recipe_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          recipe_id: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          recipe_id?: string
          created_at?: string
        }
      }

      user_ratings: {
        Row: {
          id: string
          user_id: string
          recipe_id: string
          rating: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          recipe_id: string
          rating: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          recipe_id?: string
          rating?: number
          created_at?: string
          updated_at?: string
        }
      }

      // Include existing tables if needed
      pantry_ingredients: {
        Row: {
          id: string
          name: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          created_at?: string
        }
      }
      user_pantry_items: {
        Row: {
          id: string
          user_id: string
          pantry_ingredient_id: string
          added_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          pantry_ingredient_id: string
          added_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          pantry_ingredient_id?: string
          added_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      toggle_favorite: {
        Args: {
          recipe_uuid: string
        }
        Returns: Json
      }
      set_recipe_rating: {
        Args: {
          recipe_uuid: string
          rating_value: number
        }
        Returns: Json
      }
      remove_recipe_rating: {
        Args: {
          recipe_uuid: string
        }
        Returns: Json
      }
      get_user_recipe_preferences: {
        Args: {
          recipe_uuids: string[]
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
} 